Index ready
htmlacademy-htmlcss/1856745-device-32 pull request #9
Opened 2021-11-02 01:01 UTC by andreyka9678

All page ready, except submenu and position 01 slider

2021-11-02 15:37 UTC, andreysgra requested changes
![image](https://user-images.githubusercontent.com/17790771/139872188-432d5174-8d09-4f91-a61b-9ba34322cea0.png)
Геометрия скругления краёв отличается от макета. Нужно изменить `border-radius`.

---

![image](https://user-images.githubusercontent.com/17790771/139872953-f8155675-b0b2-4d67-a87e-9412f23652bf.png)
Чтобы цифры не перекрывали текст нужно задать `slide-item` значение `z-index`, а также добавить свойство `position: relative` (чтобы заработал `z-index`).

---

Судя по тому, что в стайлгайде описаны стили и для жёлтых квадратов с изображениями, то всё это
![image](https://user-images.githubusercontent.com/17790771/139873727-8d6fb0a5-9b2f-4945-920a-b084be30268b.png)
должно являться ссылкой, а не только текст.

---

Эту линию
![image](https://user-images.githubusercontent.com/17790771/139874212-341ecba0-82e1-419b-afd9-52b764a9b8a4.png)
лучше не составлять из псевдо элементов кнопок, а описать для блока `services-button`. Это можно сделать через псевдо элемент, но можно и через свойство `border-right`.

---

![image](https://user-images.githubusercontent.com/17790771/139878064-55d36067-e0a0-413e-a17e-3abfc01e9e5e.png)
Здесь большая проблема - если кнопка находится за пределами формы, то она не отправит данные.
1. Вот это всё является формой
![image](https://user-images.githubusercontent.com/17790771/139878357-9c5c1289-730f-49c2-b57e-e97ac61a8684.png)
2. Поле для ввода `e-mail` занимает всю эту область
![image](https://user-images.githubusercontent.com/17790771/139878548-4c87440b-bd76-4c3a-b619-030b29a0ed40.png)
У вас же это какой-то маленький клочок
![image](https://user-images.githubusercontent.com/17790771/139878647-e7571507-743a-40fc-8a7f-5dc5e78e5b7a.png)

---

![image](https://user-images.githubusercontent.com/17790771/139878815-400b41ef-10e3-4629-97a4-a92b34437742.png)
Видно, что иконки не по центру ссылки. `text-align` выравнивает только по горизонтали. Чтобы выровнять иконки по обоим осям нужно изменить `display` ссылки на `flex` и выравнивание задать с помощью свойств `justify-content` и `align-items`.

2021-11-02 15:37 UTC, andreysgra commented on index.html
> +      </a>
Данный элемент интерфейса
![image](https://user-images.githubusercontent.com/17790771/139874837-f1355f3b-5711-440b-869a-f4979220975d.png)
ненавязчиво намекает на то, что при наведении курсора на него появляется всплывающая подсказка, типа такой
![image](https://user-images.githubusercontent.com/17790771/139875191-66fe4dfe-85ef-4db8-9f3d-632e7d2b6a70.png)
Хотя в стайлгайде нет на это указаний, тем не менее логика подсказывает, что это не просто декорация, следовательно нужно добавить элемент в разметку - вместо `::before` разметить кнопкой и позиционировать абсолютно относительно обёртки над ссылкой (в саму ссылку добавлять кнопку нельзя, поэтому над ссылкой `delive-item` потребуется обёртка `div`).

---

А вот здесь много лишнего в разметке:
![image](https://user-images.githubusercontent.com/17790771/139876163-31dfbd2a-a844-4610-9bd5-6a997e5993ae.png)
1. Текст оборачивать параграфом не нужно. Текст должен находится непосредственно между тегами `<a></a>`.
2. Эта часть интерфейса
![image](https://user-images.githubusercontent.com/17790771/139876508-09f2d776-2c83-4cd2-bb37-695a9688bc76.png)
рисуется за счёт `::before`.
Разметка, с учётом предыдущего комментария, про круг со знаком `!` будет такой:
```
<div> <!-- Обёртка над ссылкой -->
  <a class="delive-item" href="#">Доставим редкий товар под заказ</a>
  <button type="button"></button> <!-- Круг с восклицательным знаком -->
</div>
```

2021-11-02 21:27 UTC, andreyka9678 commented on index.html
> +      </a>
Это декорация "Количество i" относится только к модальному окну, наверное не нужно усложнять , мне бы сделать все согласно макета

2021-11-02 21:40 UTC, andreyka9678 commented on css/styles.css
> +    outline: 2px solid #AF4FFF;
Не понял как использовать псевдо класс :not(:placeholder-shown), логика понятна, но не ясно как заставить появиться button visibility: visible. Не ясно как применить  border-radius одновременно к form (input+button) что бы была общая обводка

2021-11-03 16:19 UTC, andreysgra commented on index.html
> +              <div class="navigation-link-menu-circle">
Это замечание https://github.com/htmlacademy-htmlcss/1856745-device-32/pull/9#discussion_r741150196 вы поняли неправильно. Не "Каталог товаров" нужно разметить кнопкой (это ссылка на раздел сайта каталог - кстати, в его `href` нужно указать страницу каталога), а элемент с крестиком, который у вас сейчас размечен с помощью `div` с классом `navigation-link-menu-circle`.

2021-11-03 16:19 UTC, andreysgra commented on index.html
> +      </a>
Для открытия модального окна используется сама ссылка "Доставим редкий товар под заказ".

2021-11-04 09:26 UTC, merged